
version: '3'
services:
  mysql:
    image: mysql
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_1
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - test_default

  springboot-app:
    image: school
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my_mysql:3306/test_1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "9091:8080"
    networks:
      - test_default


volumes:
  mysql-data:

networks:
  test_default:
    external: true