spring:
  server:
    port: 8080
    servlet:
      encoding:
        force-response: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    url: jdbc:mysql://my_mysql:3306/test_1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
logging:
  config: logback.xml
  level:
    com.test.mapper.UserMapper: trace

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.test.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
#datasource:
#  url: localhost:3306/test_1
##配置token生成策略
#
#
#spring:
#  redis:
#    database: 5
#    # 配置redis的主机地址，需要修改成自己的
#    host: 127.0.0.1
#    port: 6379
#
#    timeout: 5000
#    jedis:
#      pool:
#        # 连接池中的最大空闲连接，默认值也是8。
#        max-idle: 500
#        # 连接池中的最小空闲连接，默认值也是0。
#        min-idle: 50
#        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
#        max-active: 1000
#        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
#        max-wait: 2000
